# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build PacMan Project
        run: |
          cd Projects/P1
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
          cd tests
          java -cp "junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves
          java -cp "junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves
          java -cp "junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc
