# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
        - uses: actions/checkout@v2
        - name: Build Project
          run: javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
  TestPacManMove:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      container: openjdk
      steps:
        - uses: actions/checkout@v2
        - name: Test PacMan Move
          run: |
            javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestPacManMove.java
            java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
  TestMapMove:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      container: openjdk
      steps:
        - uses: actions/checkout@v2
        - name: Test Map Move
          run: |
            javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/TestMapMove.java
            java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove
