name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Build PacMan Project
        run: |
          cd Projects/P1
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/*.java tests/*.java
        
  TestPacManInRange:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test TestPacManInRange
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" Projects/P1/src/*.java tests/TestPacManMove.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManMove
